### ISSUE TITLE
Read-Only WebDAV

### ISSUE THREAD

**Issue by burnce** [UtrechtUniversity/davrods#1]
Hello,

Is there a way to make the davrods package give **read-only** access to iRODS? I would assume some configuration somewhere (apache?) could do that but pointers to where would be greatly appreciated.

Thanks,

Burnce

**Comment by tsmeele** [comment]
You can use ichmod icommand on the iRODS server to make iRODS objects read-only.    Davrods uses the user credentials to access iRODS objects and therefore will then effectively have read only access to that object.

**Comment by cjsmeele** [comment]
Hi Burnce,

The most 'correct' method to achieve this currently is setting access
controls on the iRODS side, as @tsmeele mentioned.

Davrods does not currently have a read-only setting.

As you said, you can achieve read-only access through Apache
configuration directives, for example by limiting the methods it accepts
within the Davrods vhost. However this can be considered a hacky
work-around. *It may break clients that do not expect this limitation*.

Just as an example, you can use `mod_allowmethods` (which I believe is
installed by default in httpd on CentOS) to restrict DAV access to
methods that do not modify resources, by adding
the following to your `<Location>` block:

    AllowMethods GET OPTIONS PROPFIND

Again, I cannot recommend this.
