### ISSUE TITLE
Cannot view or download files after delete files on the cache folder

### ISSUE THREAD

**Issue by Lebrero-CETEIN** [UtrechtUniversity/davrods#10]
Hi everyone, I have problems viewing or downloading files using webdav interface after I've deleted the associated files on the cache folder. 

Is there any way con configure davrods to access directly to the files store instead of the cache folder?

I don't know if this is a bug or a implemented way of use of the WebDAV interface, but in my case, I need that the files showed in the WebDAV interface will be pulled directly from the archive repository instead of the cache repo. Our archive repository is growing faster and the cache disk is too small to have a copy of ALL the data stored. 

PS: I'm using a compound resource in which the cache is stored in a local disk and the archive folder is stored in an Amazon S3 bucket... (the iRODS resource server disk is a virtual machine too, so the disk used in the machine is a virtual disk.) ...double size double cost.... 

Thank you for your help

Alejandro Lebrero

**Comment by tsmeele** [comment]
Archives accessed via compound resources are not first class resources and therefore cannot be addressed directly using the iRODS API. Hence Davrods, iCommands and other clients can only access them via their cache resource. 
At the iRODS UGM2017 an alternative driver for S3 storage has been presented that does not require a compound resource. You may want to investigate that option, a link to the presentation is [here](https://irods.org/uploads/2017/Khera-IBM-iRODS-COS-Connector-slides.pdf).

**Comment by Lebrero-CETEIN** [comment]
Thank you very much tsmeele for your accurate and fastest answer.  As you propose I will explore the IBM COS iRODS Plugin option hoping with that I can throw away the cache layer and any compound resource used to connect with S3 buckets. 

Have a nice day 

Alejandro.
