### ISSUE TITLE
Allow access via iRODS tickets

### ISSUE THREAD

**Issue by holtgrewe** [UtrechtUniversity/davrods#13]
It would be very useful to allow access via [iRODS tickets](https://docs.irods.org/4.1.3/icommands/tickets/) in one way or another. The ticket could be part of the login link (problematic for direct login as modern browsers warn if you get a `http://user:password@host` link as this is commonly used for phishing).

Another way would require another sort of authentication, which probably implies using a different (sub) domain as WebDAV has to be at the root URL for many client implementation. The ticket could also just be a query parameter as is the (infamous) session ID in early PHP/Java/... session implementations.

I have the following use case in mind.

- I need to make some files publically available via HTTPS folder/sub tree to a local UCSC genome browser instance independent of a login so it can be shared.
- Instead, you can add [track hubs](https://genome.ucsc.edu/goldenpath/help/hubQuickStart.html) in the form of a URL.
- I would like to write a script that creates a collection in iRODS and put a track hub there.
- This track hub should then be shared for a certain time and only be visible to the UCSC browser server that should access (iRODS tickets are **perfect** for this).
- The user can then add this URL to his UCSC session and UCSC browser displays the track hub's content!

E.g., I would call my custom script "publish-ucsc-track.sh local/path". The script uploads things below a predefined location on my iRODS server. It then creates a ticket and dumps a URL to the new collection in DavRods, e.g., `https://my-davrods.example.com/track-hubs/random-id?ticket=ticket-value`.

I tried to be terse here but I don't know if this request makes sense already. Let me know where this needs more work to be more clear (even if you don't consider this for immediate implementation).

**Comment by cjsmeele** [comment]
Hi Manuel,
Ticket access is a very interesting feature and we have received similar requests from other institutions.
A big question is how tickets should be provided by the client. Ideally both standard WebDAV clients and (embedded) web browsers would profit similarly from this feature.
We will investigate further and get back to you.

**Comment by holtgrewe** [comment]
Hi Chris. I realize that you are very busy and this is not high on your list but: is there any news on this?

**Comment by cjsmeele** [comment]
Hi Manuel, I'm sorry for the delayed response.
Currently I'm not able to work on new Davrods features besides maintenance, bug fixes, and releases for new iRODS versions. I expect to have more room to explore tickets around July -- I'll update this when that happens so that we may discuss here about how best to approach this feature.

**Comment by acnewton** [comment]
I am also interested in news and progress on this feature.

**Comment by cjsmeele** [comment]
Tickets for read-only access is implemented and released in [4.2.8_1.5.0](https://github.com/UtrechtUniversity/davrods/releases/tag/4.2.8_1.5.0).
[README.advanced.md](https://github.com/UtrechtUniversity/davrods/blob/master/README.advanced.md#enabling-irods-ticket-support) contains information on how this feature can be enabled. We made an effort to keep this as flexible as possible.
Please reopen this or create a new discussion if you have any questions, feedback or bugs.
