### ISSUE TITLE
davrods_merge_dir_config does not set exposed_root

### ISSUE THREAD

**Issue by QuarkDoe** [UtrechtUniversity/davrods#14]
Because compiler remove all 'assert' from release build, `assert(set_exposed_root(conf, exposed_root) >= 0);` in `davrods_merge_dir_config` never evaluated and `exposed_root` always set to "User".
The solution is to move out  `set_exposed_root` from assert.
```patch
--- a/src/config.c
+++ b/src/config.c
@@ -123,7 +123,8 @@ void *davrods_merge_dir_config(apr_pool_t *p, void *_parent, void *_child) {
     DAVRODS_PROP_MERGE(anonymous_auth_username);
     DAVRODS_PROP_MERGE(anonymous_auth_password);
 
-    assert(set_exposed_root(conf, exposed_root) >= 0);
+    int rc = set_exposed_root(conf, exposed_root);
+    assert(rc >= 0);
 
     DAVRODS_PROP_MERGE(html_head);
     DAVRODS_PROP_MERGE(html_header);
```

**Comment by cjsmeele** [comment]
Thanks for reporting this!
I suspect we never ran into this issue because we do not remove assertions in our builds and packages.
(the reason being that they provide a last-resort safety net with negligible performance impact)
We'll get this patch merged and released later this week.
