### ISSUE TITLE
Regarding use of irods_server_control_plane_key

### ISSUE THREAD

**Issue by anderbubble** [UtrechtUniversity/davrods#16]
Why does davrods require `irods_server_control_plane_key`? It appears that NFSRODS provides a similar level of access but does not require access to this key.

**Comment by tsmeele** [comment]
Where is that specified? Davrods doesn't require this key, it acts as a client.

Kind regards,

Ton

On 2 Oct 2019, at 06:54, Jonathon Anderson <notifications@github.com<mailto:notifications@github.com>> wrote:


Why does davrods require irods_server_control_plane_key? It appears that NFSRODS provides a similar level of access but does not require access to this key.

**Comment by anderbubble** [comment]
I have probably just misunderstood. The example over at

https://github.com/RENCI/docker-davrods/blob/master/README.md

Shows this value populated as part of a "minimal" config, so I assumed it
was required.

I'm planning to try deploying davrods this week, so I'll confirm it works
without that value specified. Assuming it still works perhaps I'll file a
doc bug with the docker repo.

Thanks for your help.

**Comment by anderbubble** [comment]
For the record, I've got DAVRODS working and I didn't have to specify the field in question; so this appears to just be a documentation problem over at docker-davrods.
