### ISSUE TITLE
Timeout with iRODS and Davrods.

### ISSUE THREAD

**Issue by Patkm** [UtrechtUniversity/davrods#17]
Hello,
I'm using irods for physical storage and I have an irods montage (davrods) on my ubuntu 18.04 machine of about 3To size.
The aim is to run python scripts for satellite image processing.
I successfully downloaded and stored my images (~50Go) however when i runned my python code for image processing (stack of some images) the output file never exceeded 32 MB. It increases to 32MB and then empties and refills. It is as if the maximum size was limited to 32 MB...
In the irods_environment.json file, i modified the irods_maximum_size_for_single_buffer_in_megabytes from 32 to 32000 but it didn't solve the problem.

here is a trace of log in irods (v 4.2.5)
 _**Oct 29 17:22:44 pid:8380 remote addresses: 127.0.0.1, 134.158.150.48,
193.50.94.68 ERROR: [-]
/tmp/tmppTB_kL/server/core/src/rsApiHandler.cpp:540:int
readAndProcClientMsg(rsComm_t *, int) :  status
[SYS_HEADER_READ_LEN_ERR]  errno [] -- message [only read [0] of [4]]**_

and in davrods (V 4.2.6_1.4.2-1).

_**[Tue Oct 29 18:00:22.212903 2019] [dav:error] [pid 164681] [client
193.50.94.68:45502] Unable to deliver content.  [500, #0]
[Tue Oct 29 18:00:22.212939 2019] [dav:error] [pid 164681]
(104)Connection reset by peer: [client 193.50.94.68:45502] Could not wri
te contents to filter.  [500, #0]**_
Thank's a lot for your advice
P.M.!

**Comment by cjsmeele** [comment]
Hello P.M.,

> when i runned my python code for image processing (stack of some images) the output file never exceeded 32 MB.

Could you verify whether storing >32MB files works through other means than the Python script (e.g. file manager copy operation from local disk), or were the 50GB of files uploaded using Davrods as well?

The Davrods error messages seem to point to an error during a GET operation (i.e. download from Davrods), which shouldn't occur during an PUT/upload operation. If they originate from the Python script, then it may be encountering errors during reads (and perhaps the script has more information on the error).

Kind regards,
Chris

**Comment by Patkm** [comment]
Thank you very much for your message.
Yes when i try to copy (cp) a 1GB file from local to davrods and form davrods to local, it works.
I just specify between the 2 copy operations (from local disk and to local disk) I umount and mount davrods.
This actually seems related to the python script.

**Comment by cjsmeele** [comment]
Thank you for the clarification. If you find that it is not a bug in the Python script but something that should work on Davrods, or if there is any question/uncertainty, then please re-open this issue.
Cheers,
Chris
