### ISSUE TITLE
Build fails due to missing dependencies

### ISSUE THREAD

**Issue by burnce** [UtrechtUniversity/davrods#2]
When I install all the RPMs listed in the readme, I get the following errors

````
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lboost_system
/usr/bin/ld: cannot find -lboost_filesystem
/usr/bin/ld: cannot find -lboost_regex
/usr/bin/ld: cannot find -lboost_thread
/usr/bin/ld: cannot find -lboost_chrono
/usr/bin/ld: cannot find -ljansson
collect2: error: ld returned 1 exit status
````

I have been able to build after adding the following packages:
* libstdc++-static
* boost-static
* jansson-devel

**Comment by cjsmeele** [comment]
Thanks for the report! I've added the missing dependencies to the readme.
