### ISSUE TITLE
DavRODS 4.2.9_1.5.0 .deb

### ISSUE THREAD

**Issue by BlakeGFitch** [UtrechtUniversity/davrods#25]
Hello All and thank you for the DavRODS package!

I see 4.2.9_1.5.0  is in a "pre-release" state. But I also see there is an .rpm available already.

I'm doing an Ubuntu 18 install and was planning on using your .deb. Will that be available soon or should I work-around?

Thanks,
Blake

**Comment by alanking** [comment]
I also ran into this trying to get [the iRODS demo project](https://github.com/irods/irods_demo) back up to speed as we were using the .deb in the 4.2.8-compatible version. Would appreciate an official build when you get a chance!

**Comment by BlakeGFitch** [comment]
Hi @stsnel, Hello Most Excellent DavRODS people,

We have reached that moment where a DavRODS update would, um, be most wonderful! 

Have I missed and update? And if not, would how could I better plead the case?

;-)

Best,
Blake

**Comment by stsnel** [comment]
Hi Blake,

Sorry about the delay. We hope to publish the prerelease packages tomorrow or Friday.

Best,
Sietse

**Comment by stsnel** [comment]
Prerelease Deb packages for 4.2.9 and 4.2.10 are available now at https://github.com/UtrechtUniversity/davrods/releases

We welcome any feedback regarding these prerelease versions.

**Comment by BlakeGFitch** [comment]
Hi @stsnel ,

Thanks for this! We're up and running on Ubuntu 18 and for irods 4.2.9

This proved to e a critical line. Some how, that never bit me before but caused trouble this time.
https://github.com/UtrechtUniversity/davrods/blob/2dbda3a0a582267ab17199bb9bf8503c3320beaa/aux/deb/davrods-vhost.conf#L128

This made all the difference: ichmod read public /<zone-name>/home

I don't know if the default install of irods changed or if I did that without recording it last time, but getting hung up on that left me with davrods return 404s for a while.

Thanks again!

Best,
Blake
