### ISSUE TITLE
Does DavRODS support quota requests?

### ISSUE THREAD

**Issue by deanlinssen** [UtrechtUniversity/davrods#32]
Hello!

Thanks for your development of the davrods application! We've been using it for quite a while now in the Maastricht University and are very happy with it.
Today we got a request from a user to upload large quantities of data through webdav. He cannot do it, because the mounted share in Linux shows that there is only 509G available, when the storage actually still has 14T available.

After a little digging, we found out that the value that Linux shows is just static, and doesn't change based on the value of the underlying resource and `unixfilesystem`

Is there a way for us to have Linux show the actual size of the `unixfilesystem` resource, or will it always return the values below?
```
http://upload.local.dh.unimaas.nl/ 1333333332 800000000 533333332  61% /tmp/test
``` 
A Mac will show the following values and will just allow the user to upload as much as he wants:
```
http://upload.local.dh.unimaas.nl/    0Bi    0Bi    0Bi   100%       0          0  100%   /Volumes/upload.local.dh.unimaas.nl
```

Thanks in advance!

**Comment by lwesterhof** [comment]
Does the user have 509G available on his device? Looks like https://mskb.pkisolutions.com/kb/2386902

There is a bug in the Microsoft webDAV implementation (as in not following https://www.rfc-editor.org/rfc/rfc4331). Windows client sets WebDAV mapping drive’s capacity the same as its System Drive.

**Comment by deanlinssen** [comment]
No, we verified this on three separate machines in two different environments, so that is not the case

**Comment by deanlinssen** [comment]
Hey Lazlo,

We found out that the bug with the total size showing is due to Davfs2 and does not seem to have anything to do with davrods per se.
