### ISSUE TITLE
Is a package for debian 12 planned ? 

### ISSUE THREAD

**Issue by technics3** [UtrechtUniversity/davrods#33]
I'm currently trying to deploy davrods on a debian 12 environment, as a standalone server (irods 4.3.1 is deployed on an external server).

Currently renci only ships irods-runtime 4.3.0 and 4.3.1 for Debian, and unfortunately building from source is not a reliable option for me. 

Do you plan to package a DEB for debian 12 in the future ? 

Thanks, 
technics

**Comment by stsnel** [comment]
We intend to release a DEB package for DavRODS with iRODS 4.3.1 in the future, however it may take a while before we get around to it due to limited available time.

**Comment by technics3** [comment]
Thanks a lot for responding. 

I'll keep myself inform, good luck with this.
