### ISSUE TITLE
Building with iRODS 4.2 client libraries

### ISSUE THREAD

**Issue by cjsmeele** [UtrechtUniversity/davrods#4]
Due to a restructuring of the client libraries in iRODS 4.2, Davrods currently fails to build against this iRODS version.

**Comment by bzizou** [comment]
+1
is there an hope for this to be fixed quickly or should we try to fix it by ourself?

**Comment by cjsmeele** [comment]
The version currently on the [irods-4.2-libs](https://github.com/UtrechtUniversity/davrods/tree/irods-4.2-libs) branch compiles and runs with iRODS 4.2 client libraries. I have yet to do more extensive testing, but as no changes to the code itself were necessary, I expect it to work without issues.

I will be packaging this as a pre-release version soon (as iRODS 4.2 is still marked unstable).

**Comment by bzizou** [comment]
Will test it soon I think! Thank you!

**Comment by cjsmeele** [comment]
I have tested the irods-4.2-libs branch and created release [4.2_1.1](https://github.com/UtrechtUniversity/davrods/releases/tag/4.2_1.1).

As iRODS 4.2 has been officially released, our master branch now tracks the version of Davrods that uses the 4.2 client libraries. We will continue to support the 4.1 version, which now resides in the [irods-4.1-libs](https://github.com/UtrechtUniversity/davrods/tree/irods-4.1-libs) branch.
