### ISSUE TITLE
Found a minor bug?

### ISSUE THREAD

**Issue by ilarik** [UtrechtUniversity/davrods#5]
Hi, 

Thanks for the brilliant WebDAV!

I might have discovered a minor bug, might be configuration too but you might want to check.

If I open http URL:s in a browser like `http://ridgehead.pdc.kth.se/home/ilarik` without the trailing slash, the directory listing has invalid links like `http://ridgehead.pdc.kth.se:8080/home/firstdir/` which should be `http://ridgehead.pdc.kth.se:8080/home/ilarik/firstdir/`.

If I add the trailing slash to the URL like `http://ridgehead.pdc.kth.se:8080/home/ilarik/` everything works peachy in the links in the generated index pages.

**Comment by tsmeele** [comment]
Reproduced and flagged as a bug.

**Comment by cjsmeele** [comment]
Thanks for the report!
I'm currently preparing `4.2_1.1.1` and `4.1_1.1.1` which will include this fix.
