### ISSUE TITLE
wrong lib name version 4.2.0 / 4.2.1

### ISSUE THREAD

**Issue by sferry** [UtrechtUniversity/davrods#6]
Update : 
I by passed this problem with a link to the dir /usr/lib64 instead of /usr.lib
end.

Using the 4.2_1.1.1 rpm , at the start of httpd, an error came up: 

Jul 17 10:57:02 foo.foo.fr httpd[8255]: httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/conf.modules.d/10-davrods.conf: Cannot load modules/mod_davrods.so into server: libirods_client.so**.4.2.0**: cannot open shared object file: No such file or directory

Jul 17 10:57:02 foo.foo.fr systemd[1]: httpd.service: main process exited, code=exited, status=1/FAILURE

This is because the lib version installed are : 4.2.1 NOT 4.2.0
Can you fix that / How can i fix that ?

Thx
Cheers
S.

**Comment by cjsmeele** [comment]
Thanks for the report.

I assume you mean that you made a link from libirods_client 4.2.0 to
4.2.1?
While Davrods may appear to work without issues using this workaround,
we cannot guarantee its stability in that configuration.

I'm reopening this issue to fix this:

- [ ] The iRODS client lib breaks binary compatibility between versions
  4.2.0 and 4.2.1. To resolve this we will create a new Davrods package
  for iRODS 4.2.1.

- [ ] The current Davrods package `4.2_1.1.1` incorrectly allows
  irods-runtime-4.2.1 to fill the client lib dependency - it is as you
  noticed only compatible with irods-runtime-4.2.0. We'll need to fix
  this dependency as well by releasing a new RPM.

Cheers,

Chris

**Comment by sferry** [comment]
Nice, thanks!
Waiting for the release then…

In fact there were 2 issues;
-1
the location :
Where the libs are installed
/usr/lib
Where the package search for it
/usr/lib64
-2
the version.

I figured the directory problem afterwards,
so for now I extracted the 4.2.0 lib from the irods-runtime-4.2.0 and copied it to /usr/lib64.

Cheers
Sophie

De : Chris Smeele [mailto:notifications@github.com]
Envoyé : mardi 18 juillet 2017 08:25
À : UtrechtUniversity/davrods <davrods@noreply.github.com<mailto:davrods@noreply.github.com>>
Cc : FERRY Sophie <sophie.ferry@cea.fr<mailto:sophie.ferry@cea.fr>>; State change <state_change@noreply.github.com<mailto:state_change@noreply.github.com>>
Objet : Re: [UtrechtUniversity/davrods] wrong lib name version 4.2.0 / 4.2.1 (#6)


Thanks for the report.

I assume you mean that you made a link from libirods_client 4.2.0 to
4.2.1?
While Davrods may appear to work without issues using this workaround,
we cannot guarantee its stability in that configuration.

I'm reopening this issue to fix this:

·         [ ] The iRODS client lib breaks binary compatibility between versions
4.2.0 and 4.2.1. To resolve this we will create a new Davrods package
for iRODS 4.2.1.

·         [ ] The current Davrods package 4.2_1.1.1 incorrectly allows
irods-runtime-4.2.1 to fill the client lib dependency - it is as you
noticed only compatible with irods-runtime-4.2.0. We'll need to fix
this dependency as well by releasing a new RPM.

Cheers,

Chris

**Comment by cjsmeele** [comment]
We've released Davrods version [`4.2.1_1.1.1`](https://github.com/UtrechtUniversity/davrods/releases/tag/4.2.1_1.1.1) for iRODS 4.2.1 client libraries.
Please reopen this issue if you have any library/version issues with the new release.

Cheers,

Chris
