### ISSUE TITLE
Davdrods 4.1. and remote zones

### ISSUE THREAD

**Issue by chStaiger** [UtrechtUniversity/davrods#7]
In general when you are working with federated iRODS instances, your users would need read access to the root (*/*), zone (*/<myZone>* and other zones) and home (*/<myZone>/home*) collections to list all possible federated zones they might have access to. This does not work with Davrods. When changing the view to 
 
 ```sh
 DavRodsExposedRoot  /
 ```
  users will just see an empty folder as entry point in their webdav client.

**Comment by cjsmeele** [comment]
Can you confirm that your users have `read` permissions set on both the `/` and `/zonename` collections in iRODS? These collections are not public-readable by default.

**Comment by chStaiger** [comment]
Yes, the root collection and zone are readable by the group 'public':

```sh
[admincentos@malet-server ~]$ ils -A /
/:
        ACL - g:public#maletZone:read object   rods#maletZone:own   g:rodsadmin#maletZone:delete object
        Inheritance - Disabled
  C- /maletZone
```

```sh
[admincentos@malet-server ~]$ ils -A /maletZone
/maletZone:
        ACL - g:public#maletZone:read object   rods#maletZone:own
        Inheritance - Disabled
  C- /maletZone/home
```
